name: Benchmark
on:
  pull_request: {}
  workflow_dispatch: {}
  
permissions:
  contents: read
  id-token: write

jobs:
  build-with-ut:
    name: Build with UT
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.5"
      - name: Test UTs
        run: |
          gradle --no-build-cache clean test --continue
